microsoft/monaco-languages

- README.md
closes https://github.com/Microsoft/monaco-css/issues/4
> :memo: :rose:

- gulpfile.js
- src/monaco.contribution.ts
- src/msdax.ts
- test/all.js
- test/msdax.test.ts
Basic highlight support for Microsoft SQL Analysis Services DAX language (https://msdn.microsoft.com/en-us/library/gg413422.aspx). Thanks in advance for consideration.
> MSDAX support

- scripts/bundle.js
- src/monaco.contribution.ts
- src/scheme/scheme.contribution.ts
- src/scheme/scheme.test.ts
- src/scheme/scheme.ts
- test/setup.js
Pretty simple tokenization. I think I've covered most of it.
> Add Scheme language

- README.md
When implementing a new language should be charged update
README (keep project up to date)
> upgrade all language support (today)

- README.md
- package-lock.json
- scripts/bundle.js
- src/clojure/clojure.contribution.ts
- src/clojure/clojure.test.ts
- src/clojure/clojure.ts
- src/monaco.contribution.ts
- test/setup.js
refs:
https://github.com/Microsoft/monaco-editor/issues/828
https://github.com/theia-ide/theia/issues/1717
> Clojure support

- scripts/bundle.js
- src/monaco.contribution.ts
- src/shell/shell.contribution.ts
- src/shell/shell.test.ts
- src/shell/shell.ts
- test/setup.js
Basic shell/bash language tokenization support.
> Add Shell language

- src/markdown/markdown.ts
Coloring was failing in a specific condition.
> Markdown bug fix for #1107

- src/markdown/markdown.ts
Fixes issue: https://github.com/Microsoft/monaco-editor/issues/1107
> Fix markdown bug #1107

- scripts/bundle.js
- src/kotlin/kotlin.contribution.ts
- src/kotlin/kotlin.test.ts
- src/kotlin/kotlin.ts
- src/monaco.contribution.ts
- test/setup.js
Here is my first attempt at adding Kotlin sytnax highlighting. Is there a way I can test this online in the highlighter preview? I'd like to try out some permutations.
> Add Kotlin Language Support

- README.md
- scripts/bundle.js
- src/monaco.contribution.ts
- src/pascaligo/pascaligo.contribution.ts
- src/pascaligo/pascaligo.test.ts
- src/pascaligo/pascaligo.ts
- test/setup.js
**Summary**
Pascaligo is a layer 2 smart contract language for the Tezos blockchain.
For more info please see: https://ligolang.org/
> pascaligo: adding pascaligo language support

- src/julia/julia.contribution.ts
- src/julia/julia.test.ts
- src/julia/julia.ts
- src/monaco.contribution.ts
Self-explanatory I think. Decided to get creative with the different quoting constructs like `:(...)` and `$(...)`
> Add support for Julia

- src/r/r.contribution.ts
Fixes  issue [#1821 ](https://github.com/microsoft/monaco-editor/issues/1821). 
Let me know if there's anything else that needs to be added (or changed). Thanks :)
> Added ".rmd" file extension to R's list of supported languages

- .vscode/settings.json
- src/lexon/lexon.contribution.ts
- src/lexon/lexon.test.ts
- src/lexon/lexon.ts
- src/monaco.contribution.ts
Highlighting for the [Lexon](http://lexon.tech) programming language.
> Implemented Lexon highlighting

- src/abap/abap.test.ts
- src/abap/abap.ts
Been collecting some bugs for ABAP highlighting, this PR fixes the currently known bugs.
ABAP is a crazy language, so there is probably more to fix 😄 
closes https://github.com/abaplint/abaplint/issues/554
> [ABAP] Language fixes

- src/vb/vb.test.ts
- src/vb/vb.ts
Hopefully closes microsoft/monaco-editor#1958 and microsoft/monaco-editor#1941
> [vb] fix string literals

- src/monaco.contribution.ts
- src/systemverilog/systemverilog.contribution.ts
- src/systemverilog/systemverilog.test.ts
- src/systemverilog/systemverilog.ts
Adding support in monaco-languages for SystemVerilog
Based off of this issue:
https://github.com/microsoft/monaco-editor/issues/2048
> Add Systemverilog language support

- src/hcl/hcl.contribution.ts
- src/hcl/hcl.ts
- src/monaco.contribution.ts
Hello, this is just an initial effort to push terraform language to the repo. 
I know it's still missing some things but before I commit that much time, I wanted to know if this is something that would be merged if complete. 
Some guidance about missing or required work would be also very welcome
Thank you
( https://github.com/microsoft/monaco-editor/issues/1710 )
> Adding hcl / terraform language

- src/hcl/hcl.contribution.ts
- src/hcl/hcl.test.ts
- src/hcl/hcl.ts
Here they are the tests as promised. I fetch them from the official language repo, so they should be relatively good.
I had some doubts about which token class to use because of coloring and I focused mainly on the final look considering the terraform extension for vscode
regardless if something is wrong let me know and I'll fix it
> Terraform HCL : Fixing, Improving, adding tests

- src/m3/m3.contribution.ts
- src/m3/m3.test.ts
- src/m3/m3.ts
- src/monaco.contribution.ts
This commit adds support for the Modula-3 language.
> Add Modula-3 support

- src/redshift/redshift.ts
fixes https://github.com/microsoft/monaco-editor/issues/2275
I just copied how the base [`sql`](https://github.com/microsoft/monaco-languages/blob/master/src/sql/sql.ts#L135) file did it.
> Fix highlighting of GROUP BY for redshift

- src/cpp/cpp.test.ts
- src/cpp/cpp.ts
* Uses some simple highlighting within annotations
* Supports multi-line annotations
(see compiler-explorer/compiler-explorer#878)
> Support better C++ annotation highlighting

- src/bicep/bicep.contribution.ts
- src/bicep/bicep.test.ts
- src/bicep/bicep.ts
- src/monaco.contribution.ts
Add support for [Bicep](https://github.com/Azure/bicep) language
Closes https://github.com/Azure/bicep/issues/2333
> Add support for Bicep language

- src/javascript/javascript.test.ts
- src/typescript/typescript.test.ts
- src/typescript/typescript.ts
The RegExp Match Indices proposal which adds the new RegExp flag `d` is now Stage 4 (https://github.com/tc39/proposal-regexp-match-indices)
> [JS/TS] Add support for the RegExp Match Indices flag

- src/monaco.contribution.ts
- src/qsharp/qsharp.contribution.ts
- src/qsharp/qsharp.test.ts
- src/qsharp/qsharp.ts
Add support for [Q#](https://docs.microsoft.com/en-us/azure/quantum/user-guide/language/)
> Add support for Q#

- src/flow9/flow9.contribution.ts
- src/flow9/flow9.test.ts
- src/flow9/flow9.ts
- src/monaco.contribution.ts
Add support for Flow9 language
> Implement syntax highlighting for Flow9

- src/java/java.test.ts
- src/java/java.ts
Fixes https://github.com/microsoft/monaco-editor/issues/2677
> Support Java 12-17 syntax
