src/csharp.ts
=> csharp: allow styling #r/#load

src/go.ts, test/go.test.ts
Go allows raw string literals using backquotes:
https://golang.org/ref/spec#String_literals
I'm not sure what the rules are on escaping inside raw string literals. This PR could be a starting point.
Thanks!
=> Go: add raw string literal syntax

gulpfile.js, src/monaco.contribution.ts, src/yaml.ts, test/all.js, test/yaml.test.ts, tsconfig.json
=> YAML colorization

src/csharp.ts, test/csharp.test.ts
Note that proper `_` usage is not enforced; this matches vscode behavior.
=> csharp: add support for binary literals and _ as separator

.npmignore
It would be nice to consume sources as it is to bundle it with not amd loader, e.g. it is hard to consume generated amd modules with webpack.
=> Include src as a part of npm package

src/sql.ts
I think `LIMIT` should be an included keyword for SQL, considering `OFFSET` is already included in the list
=> Add LIMIT to sql keywords

src/dockerfile.ts
Docker added `SHELL` and `STOPSIGNAL` instructions in 1.12. These should be included in the dockerfile.ts language definition file.
=> Update Dockerfile grammar with STOPSIGNAL and SHELL instructions

src/r.ts
This is primarily useful for ligature fonts that have contextual alignment for hex sequences, in my case
https://github.com/tonsky/FiraCode
=> Add hex number tokenization to R language

src/cpp.ts, test/cpp.test.ts
This pull request fix issue Microsoft/monaco-editor#687.
=> Whitespaces after # are allowed in C++ preprocessor statements (Microsoft/monaco-editor#687)

gulpfile.js, src/csp.ts, src/monaco.contribution.ts, test/all.js, test/csp.test.ts
Content-Security-Policy is a great W3C standard to prevent XSS attacks. We would love to contribute the syntax highlighting for it.
https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy
=> Support Content-Security-Policy syntax highlighting 

src/python/python.ts
Adds rules for auto indent using `onEnterRules`.
Q: I Initially tried using `indentationRules` but `decreaseIndentPattern` seemed tricky in python. Any reason to use one over the other?
=> Add auto-indentation for python

src/javascript/javascript.test.ts, src/typescript/typescript.test.ts, src/typescript/typescript.ts
Hi,
this PR does three things
1. Recognize `s` as a valid regular expression flag
2. Tokenize the flag part of regular expressions as `keyword.other` like VS Code does
3. Add more tests for regular expressions
Let me know what you think.
Thanks!
=> Improve tokenization of regular expressions

src/javascript/javascript.test.ts, src/typescript/typescript.test.ts, src/typescript/typescript.ts
Hi,
according to the [ECMAScript spec](https://tc39.github.io/ecma262/#prod-OctalIntegerLiteral) octal integer literals can also be of the form `0o123` or `0O123`. This PR adds support for that syntax and also adds some more tests for hex and binary integer literals.
Thanks!
=> [JS/TS] Add support for alternative octal integer literal syntax

src/yaml/yaml.test.ts, src/yaml/yaml.ts
I made it so that single quote strings do not escape characters.
I also added tests to check if my fix works :)
=> Fix yaml string tokenization

src/yaml/yaml.test.ts, src/yaml/yaml.ts
- Update test
- Rule for non-teminated string return `string.invalid.yaml`
=> New rule for non-teminated string in yaml

src/csharp/csharp.contribution.ts
As Cake scripts are C# scripts it would be nice to have them syntax highlighted
=> Use C# highlighting for Cake scripts

src/solidity/solidity.ts
Since Solidity v0.4.23, Solidity has new constructor notation.
```
contract Foo {
constructor() public {
// ...
}
}
=> Solidity - add "constructor" to main keywords

README.md, scripts/bundle.js, src/graphql/graphql.contribution.ts, src/graphql/graphql.test.ts, src/graphql/graphql.ts, src/monaco.contribution.ts, test/setup.js
Add GraphQL coloring and delegates block strings (mostly [used for descriptions](https://facebook.github.io/graphql/draft/#sec-Descriptions)) to markdown
=> GraphQL language support

src/clojure/clojure.contribution.ts, src/clojure/clojure.test.ts, src/clojure/clojure.ts
This PR:
- Adds ".cljs" and ".cljc" to source file name extension list
- Adds a word boundary to ensure exact matches for `(comment ...)` forms
- Improves the regular expressions for various symbols
- Removes a file name extension that's uncommon
=> [clojure] Improve the regular expressions for various symbols

src/ruby/ruby.ts
Copied rules from `vscode/extensions/ruby/language-configuration.json`
=> Update ruby auto indentation rules

README.md, scripts/bundle.js, src/monaco.contribution.ts, src/pascal/pascal.contribution.ts, src/pascal/pascal.test.ts, src/pascal/pascal.ts, test/setup.js
Adds basic Pascal language support, with syntax highlighting, auto-closing pairs and code folding.
=> Pascal language support

src/markdown/markdown.ts
Currently, syntax highlighting for code blocks in markdown files fails if you have anything after the language name other than whitespace.
example:
```
```python {annotation: test}
for x in y:
x = 5
``` 
VSCode allows you to put annotation in code block headers, so this pull request fixes the syntax highlighting to match VSCode's behavior. The ability to add annotation is important for interactive computing tools like rmarkdown or imarkdown.
=> allows annotation in markdown language block headers

src/javascript/javascript.test.ts, src/typescript/typescript.test.ts, src/typescript/typescript.ts
[monaco-typescript](https://github.com/Microsoft/monaco-typescript) now supports a TypeScript version that can handle BigInt values. This PR adds support to highlight them correctly.
Thanks!
=> [JS/TS] Add support for BigInt

src/xml/xml.contribution.ts
* Add support for [EPUB 3 .opf files](https://www.edrlab.org/epub/anatomy-of-an-epub-3-file/) as XML.
* Add support for [XSL files](https://www.w3.org/Style/XSL/) as XML.
=> [xml] Add OPF and XSL file extensions

src/mips/mips.contribution.ts, src/mips/mips.test.ts, src/mips/mips.ts, src/monaco.contribution.ts, test/setup.js
Defined rules for statements and declaration. Provided with set of keywords and variable declaration technique.
Signed-off-by: Progyan Bhattacharya <bprogyan@gmail.com>
=> [Feat] MIPS: Support for Syntax Highlight and Basic Colorization

scripts/bundle.js, src/monaco.contribution.ts, src/sophia/sophia.contribution.ts, src/sophia/sophia.test.ts, src/sophia/sophia.ts, test/setup.js
Adding support for Sophia ML smart contract language for aeternity blockchain.
=> Add support for Sophia ML

src/sophia/sophia.ts
Adding `None` and `Some` keywords for SophiaML syntax.
=> add `None` and `Some` keywords to SophiaML

README.md
+ align adding new langauge example, some of it used `sql` and some `myLang`
+ add code for monaco.contribution.ts
+ change comma to semicolon
=> readme: align "add new language" example

README.md, scripts/bundle.js, src/monaco.contribution.ts, src/twig/twig.contribution.ts, src/twig/twig.test.ts, src/twig/twig.ts, test/setup.js
This pull request adds support for the Twig template language widely used in the PHP community.
Development is paid for by [teraone](https://www.teraone.de/).
=> Add support for the Twig template language

README.md, scripts/bundle.js, src/abap/abap.contribution.ts, src/abap/abap.test.ts, src/abap/abap.ts, src/monaco.contribution.ts, test/setup.js
[ABAP] Add ABAP language support
=> [ABAP] Add ABAP language support

src/markdown/markdown.ts
New styles used are `keyword.table.{header,left,middle,right}`.
=> Adds Markdown Table syntax highlighting

README.md, scripts/bundle.js, src/cameligo/cameligo.contribution.ts, src/cameligo/cameligo.test.ts, src/cameligo/cameligo.ts, src/monaco.contribution.ts, test/setup.js
CameLigo is a smart-contract language for Tezos blockchain. For more information please see https://ligolang.org
=> Adds cameligo language support

src/st/st.test.ts, src/st/st.ts
Fixing some spellings, adding new keywords, improving regex.
=> Improvements to ST language

src/graphql/graphql.test.ts, src/graphql/graphql.ts
thought i would add a tokenizer that adds a bit more definition. let me know what you think of my useage of the identifiers? we basically have typed, named function parameters.
adding this for our upcoming custom `monaco-graphql`, and for other folks using monaco with graphql language.
the next PR I'll come up with will be to add a tokenizer that targets just the argument names (the names in the named parameters)
before:
after:
=> add tokenizer for graphql language variables

src/tcl/tcl.ts
Tcl allows functions to contain more than just alphanumeric characters so I changed that
=> Highlight function definitions better

src/swift/swift.test.ts, src/swift/swift.ts
Adds support for multiline comments in Swift and fixes [#1381](https://github.com/microsoft/monaco-editor/issues/1381).
=> Add support for multiline comments in Swift

.mocharc.json, .npmignore, test/mocha.opts
This fixes the deprecation warning
> (node:3202) DeprecationWarning: Configuration via mocha.opts is DEPRECATED and will be removed from a future version of Mocha. Use RC files or package.json instead.
see
https://dev.azure.com/ms/monaco-languages/_build/results?buildId=65072&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=bd05475d-acb5-5619-3ccb-c46842dbc997&l=18
when running tests
**PLUS**: `.editorconfig` and `azure-pipelines.yml` are now npm ignored
=> Mocha, fix deprecation warning regarding mocha.opts

src/python/python.ts
This supports https://github.com/microsoft/monaco-editor/issues/1762.
Note the new Python 3 keywords are:
* `async`
* `await`
* `nonlocal`
I also reorganized the list a bit because it seems like it contains
a mixture of keywords and builtins (and `self`, which is neither...),
so it is helpful to be specific to illustrate how to properly maintain
the list.
=> Update Python grammar to include keywords introduced in Python 3

src/javascript/javascript.contribution.ts
VSCode already supports `.mjs` as a JavaScript file :rose:
=> add .mjs support :rose:

src/handlebars/handlebars.test.ts, src/handlebars/handlebars.ts
This updates the tokenization to support mustaches in
block comments per the handlebars documentation [1].
[1] https://handlebarsjs.com/guide/#template-comments
=> Updates the comment tokenization for handlebars syntax.

src/typescript/typescript.ts
Also, while I'm in here, consolidate typeKeywords into keywords in order to make it easier to keep this in sync with TypeScript going forward. I'm assuming that typeKeywords is not part of Monaco's public API that third-party integrations are supposed to depend on; if it is, then I can undo this.
Fixes: microsoft/monaco-editor#1978
=> Add asserts, bigint, and unknown to TypeScript keywords

src/monaco.contribution.ts, src/scala/scala.contribution.ts, src/scala/scala.test.ts, src/scala/scala.ts
This PR introduces preliminary Scala support (highly inspired by src/java content) with files listed as:
src/scala/scala.contribution.ts
src/scala/scala.test.ts
src/scala/scala.ts
and modified src/monaco.contribution.ts accordingly.
=> introduce preliminary Scala support, highly inspired by src/java content

src/xml/xml.ts
This adds auto indentation in somewhat the same way as HTML does it. The difference is that there aren't any predefined self-closing tags in XML.
=> Add auto indent for xml

src/hcl/hcl.test.ts, src/hcl/hcl.ts
This fixes a bug when spaces are added before the heredoc termination
```
command = <<-EOF
string
EOF
```
was working
```
command = <<-EOF
string
EOF
```
was not and it should
=> terraform Fix heredoc

src/csharp/csharp.ts
Please see C# language specification: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/introduction
=> Property is not a keyword in C#

src/liquid/liquid.contribution.ts, src/liquid/liquid.test.ts, src/liquid/liquid.ts, src/monaco.contribution.ts
Using the Handlebars language implementation as a base, added support for Shopify's [Liquid templating language](https://shopify.github.io/liquid/). 
One thing I wanted to ask is: what are the current best practices for languages that can implemented inside other languages? From what I can see in Handlebars, Markdown, etc is that basically they had to re-implement support for HTML as I did. I was wondering though if it'd be possible to instead extend for example the HTML or CSS language implementations and then use `nextEmbedded` to add support for Liquid?
Cheers! Looking forward to some feedback on my first contribution 😄
=> Add basic language support for Liquid 

src/elixir/elixir.contribution.ts, src/elixir/elixir.test.ts, src/elixir/elixir.ts, src/monaco.contribution.ts
This comes directly from a project we are currently working on. The tokenizer is quite detailed to handle various specifics and it also provides a more extended token set, that allowed us to define a more precise theme. Below you can see both our custom theme, as well as how it fits with the default one.
<details>
<summary>One Dark port</summary>
</details>
<details>
<summary>Default theme</summary>
</details>
=> Add Elixir language definition and tokenizer

src/liquid/liquid.contribution.ts
Turns out the convention is to have .liquid after .html. Also, I didn't implement liquid with CSS so removed that
=> Fix incorrect filenames for liquid

src/liquid/liquid.contribution.ts
liquid should be findable using `Liquid` or `liquid` as the language.
=> Add aliases and mimetypes to liquid language

src/typescript/typescript.ts
TypeScript 4.3 defines a new keyword `override`. Feel free to wait with the merge until https://github.com/microsoft/monaco-typescript/ is on 4.3.
=> [TS] Add override keyword

src/restructuredtext/restructuredtext.test.ts, src/restructuredtext/restructuredtext.ts
It fixes microsoft/monaco-editor#2484. There was a bad rule to freeze the page. 
A new case is added to test `some property = Text::ProxyLibrary::ProxyInterfaceTest::DeleteProxyInterface();`
=> improve a rule which freeze a page in restructuredText

src/swift/swift.ts
As per https://docs.swift.org/swift-book/LanguageGuide/AccessControl.html#ID5, this PR adds the missing fileprivate access modifier to the Swift definition
This should close https://github.com/microsoft/monaco-editor/issues/2560
=> Add Swift fileprivate access modifier

src/monaco.contribution.ts, src/sparql/sparql.contribution.ts, src/sparql/sparql.test.ts, src/sparql/sparql.ts
This should close [microsoft/monaco-editor#2094](https://github.com/microsoft/monaco-editor/issues/2094).
=> Implement Syntax-Highlighting for SPARQL

src/cpp/cpp.test.ts, src/cpp/cpp.ts
This PR fixes an issue where c++ continuation comment syntax was not highlighted as a comment.
```c++
// test \
test \
test
```
[https://github.com/microsoft/monaco-editor/issues/2497](https://github.com/microsoft/monaco-editor/issues/2497)
=> fix c++ comment continuation highlighting #2497

src/rust/rust.test.ts, src/rust/rust.ts
This PR fixes an issue where rust raw strings were not highlighted
```rust
r"\"
r##"now#"#"highlighted"##
```
https://github.com/microsoft/monaco-editor/issues/2552
=> fix rust raw string highlighting #2552

src/rust/rust.test.ts, src/rust/rust.ts
This PR fixes an issue where char literal were not highlighting when using escape sequences
```rust
'"'
#'\n'
```
https://github.com/microsoft/monaco-editor/issues/2481
=> fix char literal highlighting #2481

src/markdown/markdown.ts
Currently Markdown tokenizer marks both opening and closing <code>\`\`\`</code> as `string`. However, if the opening one includes language as in <code>\`\`\`elixir</code>, then the closing one is incorrectly tokenized as `variable.source`.
=> Properly tokenize fence closing in GitHub style code blocks

src/liquid/liquid.ts, src/razor/razor.ts
This PR fixes rendering of html tags with a `-` symbol (custom elements in w3c spec.) in razor & liquid. Custom tags are already rendering correctly in html:
html 
razor & liquid
=> Fix razor + liquid render of tags with a dash symbol

src/pascal/pascal.ts
This PR adds support to the `strict` keyword to Pascal language.
This keyword is defined in FreePascal (https://www.freepascal.org/docs-html/current/ref/refsu3.html#x14-130001.3.3) and Delphi (http://docwiki.embarcadero.com/RADStudio/Sydney/en/Classes_and_Objects_(Delphi))
=> Adds `strict` keyword to Pascal language

src/rust/rust.ts
They're bad for Rust lifetimes.
Fixes https://github.com/microsoft/monaco-editor/issues/2585.
=> Remove ' as an auto-closing pair for Rust

src/cpp/cpp.ts
The old config `/(ll|LL|u|U|l|L)?(ll|LL|u|U|l|L)?/` also match some wrong suffix: `lll`, `llLL`, `LLl` and so on.
So I change it to `/((l|L|ll|LL)?(u|U)?)|((u|U)?(l|L|ll|LL)?)/`
**Update**: change to `/([uU](ll|LL|l|L)|(ll|LL|l|L)?[uU]?)/`
=> fix(cpp): fix cpp language integer suffix

src/hcl/hcl.ts
The Terraform HCL documentation states that the # is the preferred and default setting for single line comments:
https://www.terraform.io/docs/language/syntax/configuration.html#comments
=> Replace // with # for line comments

src/systemverilog/systemverilog.test.ts, src/systemverilog/systemverilog.ts
Adding better syntax highlighting for user-defined primitive tables, which have their own list of symbols defined by the language (0, 1, x, ?, b, -, *, r, f, p, n).  Currently the identifiers and numbers are getting highlighted which looks OK, but adding a uniform style looks better.
Before:
After:
I'm participating in [Hacktoberfest](https://hacktoberfest.digitalocean.com/), so if this PR looks good and you don't mind, could you add the `hacktoberfest-accepted` label to it?  Thanks a lot!
=> SystemVerilog: Adding better syntax highlighting for primitive table definitions
